### ISSUE TITLE
Titles inside folded section not formatted

### ISSUE THREAD

**Issue by hektech** [dokufreaks/plugin-folded#25]
Not sure if this is supposed to work, but I do not get any formatting of titles in a folded section.  That is, it simply displays with the all the equal signs, e.g.:

=====Lost/Missing 2014 Query===== 

shows exactly as typed.  This is on 2014-09-29d "Hrun".  A <code> tag in the same folded block displays as expected.

**Comment by Parad0xMS** [comment]
I can confirm the missing titles with Hrun.

From the Plugin-Page at dokuwiki.org:
Requested Features / To Do
 - allow title formatting

I think that this is a known bug. I would love to use titles in the hidden block. Is there a Roadmap for this "Feature"?

**Comment by LarsGit223** [comment]
Titles will be rendered as simple headers now, also see #38.
