### ISSUE TITLE
Initialisation broken in mediamanager

### ISSUE THREAD

**Issue by gamma** [dokufreaks/plugin-folded#28]
This should not have to do anything with each other but the media manager currently removes the JSINFO und therefore the folded plugin can not initialise when opening the media manger which stalls everything else. I already left a comment on the DW core but it might be good to have a check in this plugin too.

**Comment by LarsGit223** [comment]
I did not notice any problems with the media manager and plugin folded on my installation. Anyway the issue should be solved now by merging "Test for JSINFO.folded in script.js, prevents javascript failure when…" #26.
