### ISSUE TITLE
Link to Playground for Plugin is Broken

### ISSUE THREAD

**Issue by JMichaelTX** [dokufreaks/plugin-folded#40]
Hi, your plugin really sounds great, but I need to test it before I install it.
This link on the DokuWiki site for your plugin is broken:
http://organact.mine.nu/dokuwiki/doku.php?id=wiki:playground

Can you please fix or provide another playground?

**Comment by LarsGit223** [comment]
The plugin is not maintained by the original author any more. That is why it is listed in the dokufreaks organization. So we can give limited support and maintenance for the plugin but I unfortunately do not know an alternative playground supporting the folded plugin. Sorry.

**Comment by LarsGit223** [comment]
There is no playground with installed folded plugin available right now so I close this as ```won't fix```.
