### ISSUE TITLE
Show fold unfold all button - Version Release 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by emilracec** [dokufreaks/plugin-folded#45]
Hi,

After upgrading to the latest version of Dokuwiki (Release 2018-04-22 "Greebo") the button in the pagetool-area that folds/unfolds all texts of the current page is not showing anymore. Could you please help me with this issue?

Thank you!
Emil

**Comment by LarsGit223** [comment]
Ahhh...yes. The menu system has been re-designed in the new DokuWiki so this plugin has to be adjusted to it. I'll try to fix this in the next days.

**Comment by LarsGit223** [comment]
Should be fixed in latest release from today. Please update and test.

**Comment by emilracec** [comment]
@LarsGit223 I've updated and everything works great again. 

Thank you for your help and providing the fix!

**Comment by Conny64** [comment]
Hi,
now I have the same problem with the actually version.
Does you have any idea?

**Comment by lpaulsen93** [comment]
@Conny64 Please provide some more information:
Which DokuWiki version do you use?
Which template do yo use?
Is your wiki accessible from outside/is it a public installation so that I could have a look myself?
