### ISSUE TITLE
Folded as displayed in a sidebar, under Mobile/Smartphone

### ISSUE THREAD

**Issue by Ikandi** [dokufreaks/plugin-folded#47]
Hi there,

Thanks for the recent Greebo update to this plugin.
I use the Folded plugin in my forthcoming wiki, which is currently in test.

There are folded blocks visible on the main page:

1) in the sidebar
2) in the main window (refer Introduction)

Both work ok on a full display, though just previously, the plugin had issues with the creation of folded ID's being generated. I would click on the Introduction section, and the folded block (numbered id=1) would open up on the sidebar. That has now been fixed by the looks of it. Great.

However, when you reduce the browser down to smartphone/mobile configuration, the folded blocks on the sidebar no longer open up. The same when viewing the wiki page on a proper smartphone too.

It would be great to get this fixed as the plugin is very useful I find.

Refer to my wiki at: https://glorydazemusic.com/wiki

Thanks.
George 'Horrie' Thatcher
Melbourne, Australia

**Comment by LarsGit223** [comment]
Hello.

I am not sure if this is a issue of the folded plugin but I have to take a deeper look. I also noticed the following similar issue on my Ubuntu desktop PC:
- I open your homepage
- I click on one of the folded items in the sidebar: it works/folds-unfolds as expected
- Now I re-size my firefox window and make it that narrow/small that the sidebar disappears
- Now I bring it back to the original size
- I click on one of the folded items in the sidebar: it does not work anymore
- I reload the page (```F5```) and then it works again

**Comment by LarsGit223** [comment]
I fixed duplicate element IDs in the current master version. Please re-install the plugin (do not care about the missing update notification in the extension manager) and test.

**Comment by LarsGit223** [comment]
@Ikandi: did you have time to test this?

**Comment by LarsGit223** [comment]
@Ikandi: any news?

**Comment by lpaulsen93** [comment]
As there was no more feedback in the meantime I assume that this is fixed. Please re-open if the issue still exists.
