### ISSUE TITLE
Unfolds only in root-pages

### ISSUE THREAD

**Issue by martk70** [dokufreaks/plugin-folded#50]
Problem after fresh installing release 2018-04-22a "Greebo" and copying in the entire data directory from the previous release "Frusterick Manners". 
Folded Plugin version 2018-04-26

The _fold / unfold all_ in the page tools does work everywhere.
Sections in pages in root do fold / unfold. 
Elsewhere in the wiki it does not, also not in a new folders+page. There it is static in the state determined in the configuration. I set this to _Unfold everything by default_ as a termporary solution. 
Should this be of help, for ownership and permissons, see below.

My installation unfortunately is not entirely ok, warning: "it seems your data directory is not properly secured" on the admin page. However this has been the case for a long time, without this problem.

Thank you for paying attention to this and making the plugin available!
Martin

-------------------------------

-rwxrwxrwx  1 www-data www-data  4058 May  2 11:12 data\pages\a.txt   **/*does fold unfold*/**
-rwxrwxrwx 1 www-data www-data 3719 Jun  5 14:18 data\pages\b\b.txt     **/*does NOT fold unfold*/**	

drwxrwxrwx 29 www-data www-data      4096 Jun  5 14:26 data\pages
drwxrwxrwx 14 www-data www-data  4096 May 16 13:34 data\pages\b

**Comment by chnchg** [comment]
This should be fixed by the patch of pull request: https://github.com/dokufreaks/plugin-folded/pull/49
