### ISSUE TITLE
Folded plugin doesn't work well in pages whose names include multi byte characters

### ISSUE THREAD

**Issue by hokkaidoperson** [dokufreaks/plugin-folded#52]
Hello, I'd like to report a bug of your plugin.

In pages whose names include multi byte characters such as Japanese, 2-byte alphabets and so on, I can't unfold the text.
These pages describes the situation.  You can unfold them only by clicking "fold/unfold all"
1. A page with Japanese name: 
https://testwiki.hkdyukkuri.space/%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%86%E3%82%B9%E3%83%88
2. A page with 2-byte alphabets' name: 
https://testwiki.hkdyukkuri.space/%EF%BD%81%EF%BD%82%EF%BD%83%EF%BD%93%EF%BD%84%EF%BD%86
3. A page whose name includes both 1-byte and 2-byte alphabets: 
https://testwiki.hkdyukkuri.space/a%EF%BD%81a

Could you investigate and solve the issue?
Thanks

**Comment by LarsGit223** [comment]
It seems I can't look at the pages because I don't have access. Also I can't read japanese. Is it possible to post a minimal wiki code example here. This would be very useful for examination and testing of the issue.

Something like this:
```
++++ Title | Short text which causes issue ++++
```

**Comment by hokkaidoperson** [comment]
Oh, sorry!
I changed the setting of ACL, so now you can access there.

The pages are written in English (just the pages' names contain Japanese characters or 2-byte alphabets).

**Comment by LarsGit223** [comment]
Please manually install the version from this URL https://github.com/dokufreaks/plugin-folded/archive/multibyte.zip. Please test and report the results.

**Comment by hokkaidoperson** [comment]
The version seems to work well.
