### ISSUE TITLE
The plugin sometimes doesn't work well in the preview screen when the folded syntax is included in the lang file "edit.txt"

### ISSUE THREAD

**Issue by hokkaidoperson** [dokufreaks/plugin-folded#54]
Hello

When the lang file "edit.txt" is customized and includes the folded plugin's syntax, it works unstably.
Specifically, the folded plugin called by "edit.txt" has the HTML id of one page (maybe the id should be like "folded_lang_edit_1" etc).  And when the name of the page being edited and the name included in the HTML id matches, the plugin doesn't work well (see the picture).
![3d4a6df4-af69-4f99-b902-5773491f8db0](https://user-images.githubusercontent.com/28753678/48071381-89492000-e21d-11e8-9000-d0e604c04540.jpeg)

Could you solve the issue?

**Comment by lpaulsen93** [comment]
@hokkaidoperson Sorry, I did not understand your error description. Can you give more details? What content did you put in ```edit.txt```?

**Comment by hokkaidoperson** [comment]
When the folded plugin's syntax is included in both the page and "edit.txt", the plugin doesn't work well because the duplication of foldable sections' id occurs.
I tested using a page and a "edit.txt," with one foldable section for each.  As a result, these two foldable sections were given the same id (folded_pagename_1).

**Comment by lpaulsen93** [comment]
I prepared a fix in the branch ```fix-duplicate-ids```. It looks good to me, I did not see duplicate id's any more. It would be great if you could test yourself with that branch, before merging it.

**Comment by hokkaidoperson** [comment]
It works well in my wiki.  Thank you very much!

**Comment by lpaulsen93** [comment]
Thanks for the quick reaction. I created and merged a pull-request with the change. See #69.
