### ISSUE TITLE
Doesn't work in preview pages

### ISSUE THREAD

**Issue by dmitry-kalashnikov** [dokufreaks/plugin-folded#57]
1. Go to page edit mode. 
2. Press "Preview" button.
3. The section is collapsed.
4. I click to expand the section but .nothing happens.

Please fix it if you can,
Thank you!

**Comment by GJRobert** [comment]
Confirming. Same here.

**Comment by luffah** [comment]
Got the opposite issue (greebo) : the section is folded in preview and once saving a change (it can be unfolded correctly -- include plugin correctly works here with folded plugin too). But when page is reloaded all section are unfolded. But the only issue i got is related to include plugin https://github.com/dokufreaks/plugin-folded/issues/51

**Comment by luffah** [comment]
I have the exact opposite. It only work in preview page (and first reloading of the page).

**Comment by Michaelsy** [comment]
For me the folded plugin works as expected. Please provide information on how your behavior can be reproduced. Otherwise, developers will hardly be able to fix it.

**Comment by lpaulsen93** [comment]
I can confirm @Michaelsy results. All seems to work fine for me. Tested with: Hogfather, DokuWiki template, latest folded plugin version, Firefox on a Ubuntu desktop PC.

@dmitry-kalashnikov @GJRobert @luffah Maybe you can re-test with updated versions. If you still get problems please report details about your environment.

**Comment by GJRobert** [comment]
Hi,
I see the latest version of **folded** plugin is 2018-07-31, which is I am using.
My DW installation is a Greebo. I'm having this issue for a couple of years.

I will test again with clean Greebo and Hogfather installations and report here soon, thanks~

**Comment by lpaulsen93** [comment]
@GJRobert Please also re-install the folded plugin once, there have been changes but we did not create a new release yet - so you will see no update message. Also see #54 which is fixed but I assume it is not your exact problem?

**Comment by GJRobert** [comment]
@lpaulsen93 Thanks a lot. Have force re-installed on a clean Hogfather instance, and folded toggles work fine in both page view and edit mode.

**Comment by lpaulsen93** [comment]
@GJRobert Thanks for the feedback, will close this now.
