### ISSUE TITLE
Don't work with Argon-Theme

### ISSUE THREAD

**Issue by Laserlicht** [dokufreaks/plugin-folded#68]
Opening/closing dosn't work on any Desktop Browser.

On mobile it is working.

Any solutions?

**Comment by LarsGit223** [comment]
It seems to work fine for me if I fold/unfold a single item. Only "Fold/unfold all" does not seem to work. Is that the issue that you are talking about?

**Comment by lpaulsen93** [comment]
**Update:** this is not caused by the JavaScript error but because of a not properly built menu in the argon theme. Also see https://github.com/IceWreck/Argon-Dokuwiki-Template/pull/43. As it is not an issue of this plugin I close this now.
