### ISSUE TITLE
new version, old date

### ISSUE THREAD

**Issue by arlt** [dokufreaks/plugin-folded#81]
a new version of the folded plugin appears with an old date in the extension manager:

```
Update: Version 2022-10-13 steht zum Download bereit.
```

**Comment by fiwswe** [comment]
Huh? That is the latest version AFAICT.

See https://github.com/dokufreaks/plugin-folded/blob/master/plugin.info.txt

**Comment by arlt** [comment]
I check the versions of all plugins once a week but the installed one is from 2020-09-24.\
Don't know why...
